### PR TITLE
Porting to Blender 2.80

### PR DESCRIPTION
**Pull request by nrgsille76**
UV image slots not available anymore - use material image instead

### CODE REVIEW

**Comment by raandoom** [comment]
Hello, thank you for your contribution :) But do you see 2.80 and 2.81 branches? Actually script already ported to 2.80 and 2.81 (there was some changes in arguments) a long time ago.
Sorry, but i cant merge your pull request to this branch, please check 2.80 and 2.81 branches and make a new pull request if needed.

**Comment by nrgsille76** [comment]
I changed the version ;)

**Comment by raandoom** [comment]
Hmmm, i fast checked your commit and i cant find any improvements for current script. Functionality is the same. Only significant changes i found is:

```
<<<<<<< patch-1
        objects = [ob for ob in sce.objects if not ob.hide_viewport and ob.select_get(view_layer=layer)]
    else:
        objects = [ob for ob in sce.objects if not ob.hide_viewport]
=======
        objects = [ob for ob in sce.objects if ob.visible_get() and ob.select_get()]
    else:
        objects = [ob for ob in sce.objects if ob.visible_get()]
>>>>>>> blender_2.81
```

Maybe i missed something. Can you explain what improvements your patch bring to current script?

**Comment by nrgsille76** [comment]
I did not noticed your blender 2.81 branch - I will close this pull request and make the changes on your actual repository

**Pull request closed without merging**
